/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'test.exe'
*/

struct PyAsyncMethods;
struct PyNumberMethods;
struct PySequenceMethods;
struct PyMappingMethods;
struct bufferinfo;
struct PyBufferProcs;
struct PyMethodDef;
struct PyMemberDef;
struct PyGetSetDef;
struct _typeobject;
struct _iobuf;
struct _dictkeysobject;
struct _ts;
struct _frame;
struct PyModuleDef_Slot;
struct _exception;
struct _TypeDescriptor;
struct _s__RTTIClassHierarchyDescriptor;
struct _s__RTTIBaseClassDescriptor;
struct _s__RTTIBaseClassArray;
struct std::exception_vtbl;
struct _s_ThrowInfo;

/* 11 */
enum tagBINDSTRING : __int32
{
  BINDSTRING_HEADERS = 0x1,
  BINDSTRING_ACCEPT_MIMES = 0x2,
  BINDSTRING_EXTRA_URL = 0x3,
  BINDSTRING_LANGUAGE = 0x4,
  BINDSTRING_USERNAME = 0x5,
  BINDSTRING_PASSWORD = 0x6,
  BINDSTRING_UA_PIXELS = 0x7,
  BINDSTRING_UA_COLOR = 0x8,
  BINDSTRING_OS = 0x9,
  BINDSTRING_USER_AGENT = 0xA,
  BINDSTRING_ACCEPT_ENCODINGS = 0xB,
  BINDSTRING_POST_COOKIE = 0xC,
  BINDSTRING_POST_DATA_MIME = 0xD,
  BINDSTRING_URL = 0xE,
  BINDSTRING_IID = 0xF,
  BINDSTRING_FLAG_BIND_TO_OBJECT = 0x10,
  BINDSTRING_PTR_BIND_CONTEXT = 0x11,
  BINDSTRING_XDR_ORIGIN = 0x12,
  BINDSTRING_DOWNLOADPATH = 0x13,
  BINDSTRING_ROOTDOC_URL = 0x14,
  BINDSTRING_INITIAL_FILENAME = 0x15,
  BINDSTRING_PROXY_USERNAME = 0x16,
  BINDSTRING_PROXY_PASSWORD = 0x17,
  BINDSTRING_ENTERPRISE_ID = 0x18,
  BINDSTRING_DOC_URL = 0x19,
  BINDSTRING_SAMESITE_COOKIE_LEVEL = 0x1A,
};

/* 16 */
enum _tagINTERNETFEATURELIST : __int32
{
  FEATURE_OBJECT_CACHING = 0x0,
  FEATURE_ZONE_ELEVATION = 0x1,
  FEATURE_MIME_HANDLING = 0x2,
  FEATURE_MIME_SNIFFING = 0x3,
  FEATURE_WINDOW_RESTRICTIONS = 0x4,
  FEATURE_WEBOC_POPUPMANAGEMENT = 0x5,
  FEATURE_BEHAVIORS = 0x6,
  FEATURE_DISABLE_MK_PROTOCOL = 0x7,
  FEATURE_LOCALMACHINE_LOCKDOWN = 0x8,
  FEATURE_SECURITYBAND = 0x9,
  FEATURE_RESTRICT_ACTIVEXINSTALL = 0xA,
  FEATURE_VALIDATE_NAVIGATE_URL = 0xB,
  FEATURE_RESTRICT_FILEDOWNLOAD = 0xC,
  FEATURE_ADDON_MANAGEMENT = 0xD,
  FEATURE_PROTOCOL_LOCKDOWN = 0xE,
  FEATURE_HTTP_USERNAME_PASSWORD_DISABLE = 0xF,
  FEATURE_SAFE_BINDTOOBJECT = 0x10,
  FEATURE_UNC_SAVEDFILECHECK = 0x11,
  FEATURE_GET_URL_DOM_FILEPATH_UNENCODED = 0x12,
  FEATURE_TABBED_BROWSING = 0x13,
  FEATURE_SSLUX = 0x14,
  FEATURE_DISABLE_NAVIGATION_SOUNDS = 0x15,
  FEATURE_DISABLE_LEGACY_COMPRESSION = 0x16,
  FEATURE_FORCE_ADDR_AND_STATUS = 0x17,
  FEATURE_XMLHTTP = 0x18,
  FEATURE_DISABLE_TELNET_PROTOCOL = 0x19,
  FEATURE_FEEDS = 0x1A,
  FEATURE_BLOCK_INPUT_PROMPTS = 0x1B,
  FEATURE_ENTRY_COUNT = 0x1C,
};

/* 21 */
enum VARENUM : __int32
{
  VT_EMPTY = 0x0,
  VT_NULL = 0x1,
  VT_I2 = 0x2,
  VT_I4 = 0x3,
  VT_R4 = 0x4,
  VT_R8 = 0x5,
  VT_CY = 0x6,
  VT_DATE = 0x7,
  VT_BSTR = 0x8,
  VT_DISPATCH = 0x9,
  VT_ERROR = 0xA,
  VT_BOOL = 0xB,
  VT_VARIANT = 0xC,
  VT_UNKNOWN = 0xD,
  VT_DECIMAL = 0xE,
  VT_I1 = 0x10,
  VT_UI1 = 0x11,
  VT_UI2 = 0x12,
  VT_UI4 = 0x13,
  VT_I8 = 0x14,
  VT_UI8 = 0x15,
  VT_INT = 0x16,
  VT_UINT = 0x17,
  VT_VOID = 0x18,
  VT_HRESULT = 0x19,
  VT_PTR = 0x1A,
  VT_SAFEARRAY = 0x1B,
  VT_CARRAY = 0x1C,
  VT_USERDEFINED = 0x1D,
  VT_LPSTR = 0x1E,
  VT_LPWSTR = 0x1F,
  VT_RECORD = 0x24,
  VT_INT_PTR = 0x25,
  VT_UINT_PTR = 0x26,
  VT_FILETIME = 0x40,
  VT_BLOB = 0x41,
  VT_STREAM = 0x42,
  VT_STORAGE = 0x43,
  VT_STREAMED_OBJECT = 0x44,
  VT_STORED_OBJECT = 0x45,
  VT_BLOB_OBJECT = 0x46,
  VT_CF = 0x47,
  VT_CLSID = 0x48,
  VT_VERSIONED_STREAM = 0x49,
  VT_BSTR_BLOB = 0xFFF,
  VT_VECTOR = 0x1000,
  VT_ARRAY = 0x2000,
  VT_BYREF = 0x4000,
  VT_RESERVED = 0x8000,
  VT_ILLEGAL = 0xFFFF,
  VT_ILLEGALMASKED = 0xFFF,
  VT_TYPEMASK = 0xFFF,
};

/* 22 */
enum tagTYSPEC : __int32
{
  TYSPEC_CLSID = 0x0,
  TYSPEC_FILEEXT = 0x1,
  TYSPEC_MIMETYPE = 0x2,
  TYSPEC_FILENAME = 0x3,
  TYSPEC_PROGID = 0x4,
  TYSPEC_PACKAGENAME = 0x5,
  TYSPEC_OBJECTID = 0x6,
};

/* 23 */
enum JOB_OBJECT_NET_RATE_CONTROL_FLAGS : __int32
{
  JOB_OBJECT_NET_RATE_CONTROL_ENABLE = 0x1,
  JOB_OBJECT_NET_RATE_CONTROL_MAX_BANDWIDTH = 0x2,
  JOB_OBJECT_NET_RATE_CONTROL_DSCP_TAG = 0x4,
  JOB_OBJECT_NET_RATE_CONTROL_VALID_FLAGS = 0x7,
};

/* 24 */
enum JOB_OBJECT_IO_RATE_CONTROL_FLAGS : __int32
{
  JOB_OBJECT_IO_RATE_CONTROL_ENABLE = 0x1,
  JOB_OBJECT_IO_RATE_CONTROL_STANDALONE_VOLUME = 0x2,
  JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ALL = 0x4,
  JOB_OBJECT_IO_RATE_CONTROL_FORCE_UNIT_ACCESS_ON_SOFT_CAP = 0x8,
  JOB_OBJECT_IO_RATE_CONTROL_VALID_FLAGS = 0xF,
};

/* 85 */
enum std::_Invoker_strategy : __int32
{
  _Functor = 0x0,
  _Pmf_object = 0x1,
  _Pmf_refwrap = 0x2,
  _Pmf_pointer = 0x3,
  _Pmd_object = 0x4,
  _Pmd_refwrap = 0x5,
  _Pmd_pointer = 0x6,
};

/* 111 */
enum _SYSTEM_INFORMATION_CLASS : __int32
{
  SystemBasicInformation = 0x0,
  SystemProcessorInformation = 0x1,
  SystemPerformanceInformation = 0x2,
  SystemTimeOfDayInformation = 0x3,
  SystemPathInformation = 0x4,
  SystemProcessInformation = 0x5,
  SystemCallCountInformation = 0x6,
  SystemDeviceInformation = 0x7,
  SystemProcessorPerformanceInformation = 0x8,
  SystemFlagsInformation = 0x9,
  SystemCallTimeInformation = 0xA,
  SystemModuleInformation = 0xB,
  SystemLocksInformation = 0xC,
  SystemStackTraceInformation = 0xD,
  SystemPagedPoolInformation = 0xE,
  SystemNonPagedPoolInformation = 0xF,
  SystemHandleInformation = 0x10,
  SystemObjectInformation = 0x11,
  SystemPageFileInformation = 0x12,
  SystemVdmInstemulInformation = 0x13,
  SystemVdmBopInformation = 0x14,
  SystemFileCacheInformation = 0x15,
  SystemPoolTagInformation = 0x16,
  SystemInterruptInformation = 0x17,
  SystemDpcBehaviorInformation = 0x18,
  SystemFullMemoryInformation = 0x19,
  SystemLoadGdiDriverInformation = 0x1A,
  SystemUnloadGdiDriverInformation = 0x1B,
  SystemTimeAdjustmentInformation = 0x1C,
  SystemSummaryMemoryInformation = 0x1D,
  SystemMirrorMemoryInformation = 0x1E,
  SystemPerformanceTraceInformation = 0x1F,
  SystemObsolete0 = 0x20,
  SystemExceptionInformation = 0x21,
  SystemCrashDumpStateInformation = 0x22,
  SystemKernelDebuggerInformation = 0x23,
  SystemContextSwitchInformation = 0x24,
  SystemRegistryQuotaInformation = 0x25,
  SystemExtendServiceTableInformation = 0x26,
  SystemPrioritySeperation = 0x27,
  SystemVerifierAddDriverInformation = 0x28,
  SystemVerifierRemoveDriverInformation = 0x29,
  SystemProcessorIdleInformation = 0x2A,
  SystemLegacyDriverInformation = 0x2B,
  SystemCurrentTimeZoneInformation = 0x2C,
  SystemLookasideInformation = 0x2D,
  SystemTimeSlipNotification = 0x2E,
  SystemSessionCreate = 0x2F,
  SystemSessionDetach = 0x30,
  SystemSessionInformation = 0x31,
  SystemRangeStartInformation = 0x32,
  SystemVerifierInformation = 0x33,
  SystemVerifierThunkExtend = 0x34,
  SystemSessionProcessInformation = 0x35,
  SystemLoadGdiDriverInSystemSpace = 0x36,
  SystemNumaProcessorMap = 0x37,
  SystemPrefetcherInformation = 0x38,
  SystemExtendedProcessInformation = 0x39,
  SystemRecommendedSharedDataAlignment = 0x3A,
  SystemComPlusPackage = 0x3B,
  SystemNumaAvailableMemory = 0x3C,
  SystemProcessorPowerInformation = 0x3D,
  SystemEmulationBasicInformation = 0x3E,
  SystemEmulationProcessorInformation = 0x3F,
  SystemExtendedHandleInformation = 0x40,
  SystemLostDelayedWriteInformation = 0x41,
  SystemBigPoolInformation = 0x42,
  SystemSessionPoolTagInformation = 0x43,
  SystemSessionMappedViewInformation = 0x44,
  SystemHotpatchInformation = 0x45,
  SystemObjectSecurityMode = 0x46,
  SystemWatchdogTimerHandler = 0x47,
  SystemWatchdogTimerInformation = 0x48,
  SystemLogicalProcessorInformation = 0x49,
  SystemWow64SharedInformationObsolete = 0x4A,
  SystemRegisterFirmwareTableInformationHandler = 0x4B,
  SystemFirmwareTableInformation = 0x4C,
  SystemModuleInformationEx = 0x4D,
  SystemVerifierTriageInformation = 0x4E,
  SystemSuperfetchInformation = 0x4F,
  SystemMemoryListInformation = 0x50,
  SystemFileCacheInformationEx = 0x51,
  SystemThreadPriorityClientIdInformation = 0x52,
  SystemProcessorIdleCycleTimeInformation = 0x53,
  SystemVerifierCancellationInformation = 0x54,
  SystemProcessorPowerInformationEx = 0x55,
  SystemRefTraceInformation = 0x56,
  SystemSpecialPoolInformation = 0x57,
  SystemProcessIdInformation = 0x58,
  SystemErrorPortInformation = 0x59,
  SystemBootEnvironmentInformation = 0x5A,
  SystemHypervisorInformation = 0x5B,
  SystemVerifierInformationEx = 0x5C,
  SystemTimeZoneInformation = 0x5D,
  SystemImageFileExecutionOptionsInformation = 0x5E,
  SystemCoverageInformation = 0x5F,
  SystemPrefetchPatchInformation = 0x60,
  SystemVerifierFaultsInformation = 0x61,
  SystemSystemPartitionInformation = 0x62,
  SystemSystemDiskInformation = 0x63,
  SystemProcessorPerformanceDistribution = 0x64,
  SystemNumaProximityNodeInformation = 0x65,
  SystemDynamicTimeZoneInformation = 0x66,
  SystemCodeIntegrityInformation = 0x67,
  SystemProcessorMicrocodeUpdateInformation = 0x68,
  SystemProcessorBrandString = 0x69,
  SystemVirtualAddressInformation = 0x6A,
  SystemLogicalProcessorAndGroupInformation = 0x6B,
  SystemProcessorCycleTimeInformation = 0x6C,
  SystemStoreInformation = 0x6D,
  SystemRegistryAppendString = 0x6E,
  SystemAitSamplingValue = 0x6F,
  SystemVhdBootInformation = 0x70,
  SystemCpuQuotaInformation = 0x71,
  SystemNativeBasicInformation = 0x72,
  SystemErrorPortTimeouts = 0x73,
  SystemLowPriorityIoInformation = 0x74,
  SystemBootEntropyInformation = 0x75,
  SystemVerifierCountersInformation = 0x76,
  SystemPagedPoolInformationEx = 0x77,
  SystemSystemPtesInformationEx = 0x78,
  SystemNodeDistanceInformation = 0x79,
  SystemAcpiAuditInformation = 0x7A,
  SystemBasicPerformanceInformation = 0x7B,
  SystemQueryPerformanceCounterInformation = 0x7C,
  SystemSessionBigPoolInformation = 0x7D,
  SystemBootGraphicsInformation = 0x7E,
  SystemScrubPhysicalMemoryInformation = 0x7F,
  SystemBadPageInformation = 0x80,
  SystemProcessorProfileControlArea = 0x81,
  SystemCombinePhysicalMemoryInformation = 0x82,
  SystemEntropyInterruptTimingInformation = 0x83,
  SystemConsoleInformation = 0x84,
  SystemPlatformBinaryInformation = 0x85,
  SystemPolicyInformation = 0x86,
  SystemHypervisorProcessorCountInformation = 0x87,
  SystemDeviceDataInformation = 0x88,
  SystemDeviceDataEnumerationInformation = 0x89,
  SystemMemoryTopologyInformation = 0x8A,
  SystemMemoryChannelInformation = 0x8B,
  SystemBootLogoInformation = 0x8C,
  SystemProcessorPerformanceInformationEx = 0x8D,
  SystemCriticalProcessErrorLogInformation = 0x8E,
  SystemSecureBootPolicyInformation = 0x8F,
  SystemPageFileInformationEx = 0x90,
  SystemSecureBootInformation = 0x91,
  SystemEntropyInterruptTimingRawInformation = 0x92,
  SystemPortableWorkspaceEfiLauncherInformation = 0x93,
  SystemFullProcessInformation = 0x94,
  SystemKernelDebuggerInformationEx = 0x95,
  SystemBootMetadataInformation = 0x96,
  SystemSoftRebootInformation = 0x97,
  SystemElamCertificateInformation = 0x98,
  SystemOfflineDumpConfigInformation = 0x99,
  SystemProcessorFeaturesInformation = 0x9A,
  SystemRegistryReconciliationInformation = 0x9B,
  SystemEdidInformation = 0x9C,
  SystemManufacturingInformation = 0x9D,
  SystemEnergyEstimationConfigInformation = 0x9E,
  SystemHypervisorDetailInformation = 0x9F,
  SystemProcessorCycleStatsInformation = 0xA0,
  SystemVmGenerationCountInformation = 0xA1,
  SystemTrustedPlatformModuleInformation = 0xA2,
  SystemKernelDebuggerFlags = 0xA3,
  SystemCodeIntegrityPolicyInformation = 0xA4,
  SystemIsolatedUserModeInformation = 0xA5,
  SystemHardwareSecurityTestInterfaceResultsInformation = 0xA6,
  SystemSingleModuleInformation = 0xA7,
  SystemAllowedCpuSetsInformation = 0xA8,
  SystemVsmProtectionInformation = 0xA9,
  SystemInterruptCpuSetsInformation = 0xAA,
  SystemSecureBootPolicyFullInformation = 0xAB,
  SystemCodeIntegrityPolicyFullInformation = 0xAC,
  SystemAffinitizedInterruptProcessorInformation = 0xAD,
  SystemRootSiloInformation = 0xAE,
  SystemCpuSetInformation = 0xAF,
  SystemCpuSetTagInformation = 0xB0,
  SystemWin32WerStartCallout = 0xB1,
  SystemSecureKernelProfileInformation = 0xB2,
  SystemCodeIntegrityPlatformManifestInformation = 0xB3,
  SystemInterruptSteeringInformation = 0xB4,
  SystemSupportedProcessorArchitectures = 0xB5,
  SystemMemoryUsageInformation = 0xB6,
  SystemCodeIntegrityCertificateInformation = 0xB7,
  SystemPhysicalMemoryInformation = 0xB8,
  SystemControlFlowTransition = 0xB9,
  SystemKernelDebuggingAllowed = 0xBA,
  SystemActivityModerationExeState = 0xBB,
  SystemActivityModerationUserSettings = 0xBC,
  SystemCodeIntegrityPoliciesFullInformation = 0xBD,
  SystemCodeIntegrityUnlockInformation = 0xBE,
  SystemIntegrityQuotaInformation = 0xBF,
  SystemFlushInformation = 0xC0,
  SystemProcessorIdleMaskInformation = 0xC1,
  SystemSecureDumpEncryptionInformation = 0xC2,
  SystemWriteConstraintInformation = 0xC3,
  SystemKernelVaShadowInformation = 0xC4,
  SystemHypervisorSharedPageInformation = 0xC5,
  SystemFirmwareBootPerformanceInformation = 0xC6,
  SystemCodeIntegrityVerificationInformation = 0xC7,
  SystemFirmwarePartitionInformation = 0xC8,
  SystemSpeculationControlInformation = 0xC9,
  SystemDmaGuardPolicyInformation = 0xCA,
  SystemEnclaveLaunchControlInformation = 0xCB,
  SystemWorkloadAllowedCpuSetsInformation = 0xCC,
  SystemCodeIntegrityUnlockModeInformation = 0xCD,
  SystemLeapSecondInformation = 0xCE,
  SystemFlags2Information = 0xCF,
  SystemSecurityModelInformation = 0xD0,
  SystemCodeIntegritySyntheticCacheInformation = 0xD1,
  SystemFeatureConfigurationInformation = 0xD2,
  SystemFeatureConfigurationSectionInformation = 0xD3,
  SystemFeatureUsageSubscriptionInformation = 0xD4,
  SystemSecureSpeculationControlInformation = 0xD5,
  SystemSpacesBootInformation = 0xD6,
  SystemFwRamdiskInformation = 0xD7,
  SystemWheaIpmiHardwareInformation = 0xD8,
  SystemDifSetRuleClassInformation = 0xD9,
  SystemDifClearRuleClassInformation = 0xDA,
  SystemDifApplyPluginVerificationOnDriver = 0xDB,
  SystemDifRemovePluginVerificationOnDriver = 0xDC,
  SystemShadowStackInformation = 0xDD,
  SystemBuildVersionInformation = 0xDE,
  SystemPoolLimitInformation = 0xDF,
  SystemCodeIntegrityAddDynamicStore = 0xE0,
  SystemCodeIntegrityClearDynamicStores = 0xE1,
  SystemDifPoolTrackingInformation = 0xE2,
  SystemPoolZeroingInformation = 0xE3,
  SystemDpcWatchdogInformation = 0xE4,
  SystemDpcWatchdogInformation2 = 0xE5,
  SystemSupportedProcessorArchitectures2 = 0xE6,
  SystemSingleProcessorRelationshipInformation = 0xE7,
  SystemXfgCheckFailureInformation = 0xE8,
  MaxSystemInfoClass = 0xE9,
};

/* 112 */
enum _JOBOBJECTINFOCLASS : __int32
{
  JobObjectBasicAccountingInformation = 0x1,
  JobObjectBasicLimitInformation = 0x2,
  JobObjectBasicProcessIdList = 0x3,
  JobObjectBasicUIRestrictions = 0x4,
  JobObjectSecurityLimitInformation = 0x5,
  JobObjectEndOfJobTimeInformation = 0x6,
  JobObjectAssociateCompletionPortInformation = 0x7,
  JobObjectBasicAndIoAccountingInformation = 0x8,
  JobObjectExtendedLimitInformation = 0x9,
  JobObjectJobSetInformation = 0xA,
  JobObjectGroupInformation = 0xB,
  JobObjectNotificationLimitInformation = 0xC,
  JobObjectLimitViolationInformation = 0xD,
  JobObjectGroupInformationEx = 0xE,
  JobObjectCpuRateControlInformation = 0xF,
  JobObjectCompletionFilter = 0x10,
  JobObjectCompletionCounter = 0x11,
  JobObjectFreezeInformation = 0x12,
  JobObjectExtendedAccountingInformation = 0x13,
  JobObjectWakeInformation = 0x14,
  JobObjectBackgroundInformation = 0x15,
  JobObjectSchedulingRankBiasInformation = 0x16,
  JobObjectTimerVirtualizationInformation = 0x17,
  JobObjectCycleTimeNotification = 0x18,
  JobObjectClearEvent = 0x19,
  JobObjectInterferenceInformation = 0x1A,
  JobObjectClearPeakJobMemoryUsed = 0x1B,
  JobObjectMemoryUsageInformation = 0x1C,
  JobObjectSharedCommit = 0x1D,
  JobObjectContainerId = 0x1E,
  JobObjectIoRateControlInformation = 0x1F,
  JobObjectSiloRootDirectory = 0x25,
  JobObjectServerSiloBasicInformation = 0x26,
  JobObjectServerSiloUserSharedData = 0x27,
  JobObjectServerSiloInitialize = 0x28,
  JobObjectServerSiloRunningState = 0x29,
  JobObjectIoAttribution = 0x2A,
  JobObjectMemoryPartitionInformation = 0x2B,
  JobObjectContainerTelemetryId = 0x2C,
  JobObjectSiloSystemRoot = 0x2D,
  JobObjectEnergyTrackingState = 0x2E,
  JobObjectThreadImpersonationInformation = 0x2F,
  JobObjectReserved1Information = 0x12,
  JobObjectReserved2Information = 0x13,
  JobObjectReserved3Information = 0x14,
  JobObjectReserved4Information = 0x15,
  JobObjectReserved5Information = 0x16,
  JobObjectReserved6Information = 0x17,
  JobObjectReserved7Information = 0x18,
  JobObjectReserved8Information = 0x19,
  JobObjectReserved9Information = 0x1A,
  JobObjectReserved10Information = 0x1B,
  JobObjectReserved11Information = 0x1C,
  JobObjectReserved12Information = 0x1D,
  JobObjectReserved13Information = 0x1E,
  JobObjectReserved14Information = 0x1F,
  JobObjectNetRateControlInformation = 0x20,
  JobObjectNotificationLimitInformation2 = 0x21,
  JobObjectLimitViolationInformation2 = 0x22,
  JobObjectCreateSilo = 0x23,
  JobObjectSiloBasicInformation = 0x24,
  JobObjectReserved15Information = 0x25,
  JobObjectReserved16Information = 0x26,
  JobObjectReserved17Information = 0x27,
  JobObjectReserved18Information = 0x28,
  JobObjectReserved19Information = 0x29,
  JobObjectReserved20Information = 0x2A,
  JobObjectReserved21Information = 0x2B,
  JobObjectReserved22Information = 0x2C,
  JobObjectReserved23Information = 0x2D,
  JobObjectReserved24Information = 0x2E,
  JobObjectReserved25Information = 0x2F,
  MaxJobObjectInfoClass = 0x30,
};

/* 115 */
enum _PS_ATTRIBUTE_NUM : __int32
{
  PsAttributeParentProcess = 0x0,
  PsAttributeDebugObject = 0x1,
  PsAttributeToken = 0x2,
  PsAttributeClientId = 0x3,
  PsAttributeTebAddress = 0x4,
  PsAttributeImageName = 0x5,
  PsAttributeImageInfo = 0x6,
  PsAttributeMemoryReserve = 0x7,
  PsAttributePriorityClass = 0x8,
  PsAttributeErrorMode = 0x9,
  PsAttributeStdHandleInfo = 0xA,
  PsAttributeHandleList = 0xB,
  PsAttributeGroupAffinity = 0xC,
  PsAttributePreferredNode = 0xD,
  PsAttributeIdealProcessor = 0xE,
  PsAttributeUmsThread = 0xF,
  PsAttributeMitigationOptions = 0x10,
  PsAttributeProtectionLevel = 0x11,
  PsAttributeSecureProcess = 0x12,
  PsAttributeJobList = 0x13,
  PsAttributeChildProcessPolicy = 0x14,
  PsAttributeAllApplicationPackagesPolicy = 0x15,
  PsAttributeWin32kFilter = 0x16,
  PsAttributeSafeOpenPromptOriginClaim = 0x17,
  PsAttributeBnoIsolation = 0x18,
  PsAttributeDesktopAppPolicy = 0x19,
  PsAttributeChpe = 0x1A,
  PsAttributeMitigationAuditOptions = 0x1B,
  PsAttributeMachineType = 0x1C,
  PsAttributeComponentFilter = 0x1D,
  PsAttributeEnableOptionalXStateFeatures = 0x1E,
  PsAttributeMax = 0x1F,
};

/* 194 */
struct _object
{
  __int64 ob_refcnt;
  _typeobject *ob_type;
};

/* 195 */
struct PyVarObject
{
  _object ob_base;
  __int64 ob_size;
};

/* 205 */
struct _typeobject
{
  PyVarObject ob_base;
  const unsigned __int8 *tp_name;
  __int64 tp_basicsize;
  __int64 tp_itemsize;
  void (__fastcall *tp_dealloc)(_object *);
  __int64 tp_vectorcall_offset;
  _object *(__fastcall *tp_getattr)(_object *, unsigned __int8 *);
  int (__fastcall *tp_setattr)(_object *, unsigned __int8 *, _object *);
  PyAsyncMethods *tp_as_async;
  _object *(__fastcall *tp_repr)(_object *);
  PyNumberMethods *tp_as_number;
  PySequenceMethods *tp_as_sequence;
  PyMappingMethods *tp_as_mapping;
  __int64 (__fastcall *tp_hash)(_object *);
  _object *(__fastcall *tp_call)(_object *, _object *, _object *);
  _object *(__fastcall *tp_str)(_object *);
  _object *(__fastcall *tp_getattro)(_object *, _object *);
  int (__fastcall *tp_setattro)(_object *, _object *, _object *);
  PyBufferProcs *tp_as_buffer;
  unsigned int tp_flags;
  const unsigned __int8 *tp_doc;
  int (__fastcall *tp_traverse)(_object *, int (__fastcall *)(_object *, void *), void *);
  int (__fastcall *tp_clear)(_object *);
  _object *(__fastcall *tp_richcompare)(_object *, _object *, int);
  __int64 tp_weaklistoffset;
  _object *(__fastcall *tp_iter)(_object *);
  _object *(__fastcall *tp_iternext)(_object *);
  PyMethodDef *tp_methods;
  PyMemberDef *tp_members;
  PyGetSetDef *tp_getset;
  _typeobject *tp_base;
  _object *tp_dict;
  _object *(__fastcall *tp_descr_get)(_object *, _object *, _object *);
  int (__fastcall *tp_descr_set)(_object *, _object *, _object *);
  __int64 tp_dictoffset;
  int (__fastcall *tp_init)(_object *, _object *, _object *);
  _object *(__fastcall *tp_alloc)(_typeobject *, __int64);
  _object *(__fastcall *tp_new)(_typeobject *, _object *, _object *);
  void (__fastcall *tp_free)(void *);
  int (__fastcall *tp_is_gc)(_object *);
  _object *tp_bases;
  _object *tp_mro;
  _object *tp_cache;
  _object *tp_subclasses;
  _object *tp_weaklist;
  void (__fastcall *tp_del)(_object *);
  unsigned int tp_version_tag;
  void (__fastcall *tp_finalize)(_object *);
  _object *(__fastcall *tp_vectorcall)(_object *, _object *const *, unsigned __int64, _object *);
  int (__fastcall *tp_print)(_object *, _iobuf *, int);
};

/* 196 */
struct PyAsyncMethods
{
  _object *(__fastcall *am_await)(_object *);
  _object *(__fastcall *am_aiter)(_object *);
  _object *(__fastcall *am_anext)(_object *);
};

/* 197 */
struct PyNumberMethods
{
  _object *(__fastcall *nb_add)(_object *, _object *);
  _object *(__fastcall *nb_subtract)(_object *, _object *);
  _object *(__fastcall *nb_multiply)(_object *, _object *);
  _object *(__fastcall *nb_remainder)(_object *, _object *);
  _object *(__fastcall *nb_divmod)(_object *, _object *);
  _object *(__fastcall *nb_power)(_object *, _object *, _object *);
  _object *(__fastcall *nb_negative)(_object *);
  _object *(__fastcall *nb_positive)(_object *);
  _object *(__fastcall *nb_absolute)(_object *);
  int (__fastcall *nb_bool)(_object *);
  _object *(__fastcall *nb_invert)(_object *);
  _object *(__fastcall *nb_lshift)(_object *, _object *);
  _object *(__fastcall *nb_rshift)(_object *, _object *);
  _object *(__fastcall *nb_and)(_object *, _object *);
  _object *(__fastcall *nb_xor)(_object *, _object *);
  _object *(__fastcall *nb_or)(_object *, _object *);
  _object *(__fastcall *nb_int)(_object *);
  void *nb_reserved;
  _object *(__fastcall *nb_float)(_object *);
  _object *(__fastcall *nb_inplace_add)(_object *, _object *);
  _object *(__fastcall *nb_inplace_subtract)(_object *, _object *);
  _object *(__fastcall *nb_inplace_multiply)(_object *, _object *);
  _object *(__fastcall *nb_inplace_remainder)(_object *, _object *);
  _object *(__fastcall *nb_inplace_power)(_object *, _object *, _object *);
  _object *(__fastcall *nb_inplace_lshift)(_object *, _object *);
  _object *(__fastcall *nb_inplace_rshift)(_object *, _object *);
  _object *(__fastcall *nb_inplace_and)(_object *, _object *);
  _object *(__fastcall *nb_inplace_xor)(_object *, _object *);
  _object *(__fastcall *nb_inplace_or)(_object *, _object *);
  _object *(__fastcall *nb_floor_divide)(_object *, _object *);
  _object *(__fastcall *nb_true_divide)(_object *, _object *);
  _object *(__fastcall *nb_inplace_floor_divide)(_object *, _object *);
  _object *(__fastcall *nb_inplace_true_divide)(_object *, _object *);
  _object *(__fastcall *nb_index)(_object *);
  _object *(__fastcall *nb_matrix_multiply)(_object *, _object *);
  _object *(__fastcall *nb_inplace_matrix_multiply)(_object *, _object *);
};

/* 198 */
struct PySequenceMethods
{
  __int64 (__fastcall *sq_length)(_object *);
  _object *(__fastcall *sq_concat)(_object *, _object *);
  _object *(__fastcall *sq_repeat)(_object *, __int64);
  _object *(__fastcall *sq_item)(_object *, __int64);
  void *was_sq_slice;
  int (__fastcall *sq_ass_item)(_object *, __int64, _object *);
  void *was_sq_ass_slice;
  int (__fastcall *sq_contains)(_object *, _object *);
  _object *(__fastcall *sq_inplace_concat)(_object *, _object *);
  _object *(__fastcall *sq_inplace_repeat)(_object *, __int64);
};

/* 199 */
struct PyMappingMethods
{
  __int64 (__fastcall *mp_length)(_object *);
  _object *(__fastcall *mp_subscript)(_object *, _object *);
  int (__fastcall *mp_ass_subscript)(_object *, _object *, _object *);
};

/* 201 */
struct PyBufferProcs
{
  int (__fastcall *bf_getbuffer)(_object *, bufferinfo *, int);
  void (__fastcall *bf_releasebuffer)(_object *, bufferinfo *);
};

/* 202 */
struct PyMethodDef
{
  const unsigned __int8 *ml_name;
  _object *(__fastcall *ml_meth)(_object *, _object *);
  int ml_flags;
  const unsigned __int8 *ml_doc;
};

/* 203 */
struct PyMemberDef
{
  const unsigned __int8 *name;
  int type;
  __int64 offset;
  int flags;
  const unsigned __int8 *doc;
};

/* 204 */
struct PyGetSetDef
{
  const unsigned __int8 *name;
  _object *(__fastcall *get)(_object *, void *);
  int (__fastcall *set)(_object *, _object *, void *);
  const unsigned __int8 *doc;
  void *closure;
};

/* 206 */
struct _iobuf
{
  void *_Placeholder;
};

/* 200 */
struct bufferinfo
{
  void *buf;
  _object *obj;
  __int64 len;
  __int64 itemsize;
  int readonly;
  int ndim;
  unsigned __int8 *format;
  __int64 *shape;
  __int64 *strides;
  __int64 *suboffsets;
  void *internal;
};

/* 207 */
struct PyDictObject
{
  _object ob_base;
  __int64 ma_used;
  unsigned __int64 ma_version_tag;
  _dictkeysobject *ma_keys;
  _object **ma_values;
};

/* 208 */
struct _dictkeysobject
{
  __int64 dk_refcnt;
  __int64 dk_size;
  __int64 (__fastcall *dk_lookup)(PyDictObject *, _object *, __int64, _object **);
  __int64 dk_usable;
  __int64 dk_nentries;
  unsigned __int8 dk_indices[];
};

/* 209 */
struct __declspec(align(4)) PyCodeObject
{
  _object ob_base;
  int co_argcount;
  int co_posonlyargcount;
  int co_kwonlyargcount;
  int co_nlocals;
  int co_stacksize;
  int co_flags;
  int co_firstlineno;
  _object *co_code;
  _object *co_consts;
  _object *co_names;
  _object *co_varnames;
  _object *co_freevars;
  _object *co_cellvars;
  __int64 *co_cell2arg;
  _object *co_filename;
  _object *co_name;
  _object *co_lnotab;
  void *co_zombieframe;
  _object *co_weakreflist;
  void *co_extra;
  unsigned __int8 *co_opcache_map;
  struct _PyOpcache *co_opcache;
  int co_opcache_flag;
  unsigned __int8 co_opcache_size;
};

/* 210 */
struct PyModuleObject
{
  _object ob_base;
  _object *md_dict;
};

/* 212 */
struct _err_stackitem
{
  _object *exc_type;
  _object *exc_value;
  _object *exc_traceback;
  _err_stackitem *previous_item;
};

/* 213 */
struct $72F7FB1F800070614D4CB710E4B52B7F
{
  unsigned __int32 interned : 2;
  unsigned __int32 kind : 3;
  unsigned __int32 compact : 1;
  unsigned __int32 ascii : 1;
  unsigned __int32 ready : 1;
};

/* 1046 */
typedef unsigned __int16 wchar_t;

/* 214 */
struct PyASCIIObject
{
  _object ob_base;
  __int64 length;
  __int64 hash;
  $72F7FB1F800070614D4CB710E4B52B7F state;
  wchar_t *wstr;
};

/* 215 */
struct PyCompactUnicodeObject
{
  PyASCIIObject _base;
  __int64 utf8_length;
  unsigned __int8 *utf8;
  __int64 wstr_length;
};

/* 216 */
union $EE30E1B4A0DFAF17EF4C083609A036CF
{
  void *any;
  unsigned __int8 *latin1;
  unsigned __int16 *ucs2;
  unsigned int *ucs4;
};

/* 217 */
struct PyUnicodeObject
{
  PyCompactUnicodeObject _base;
  $EE30E1B4A0DFAF17EF4C083609A036CF data;
};

/* 38 */
enum _Py_error_handler : __int32
{
  _Py_ERROR_UNKNOWN = 0x0,
  _Py_ERROR_STRICT = 0x1,
  _Py_ERROR_SURROGATEESCAPE = 0x2,
  _Py_ERROR_REPLACE = 0x3,
  _Py_ERROR_IGNORE = 0x4,
  _Py_ERROR_BACKSLASHREPLACE = 0x5,
  _Py_ERROR_SURROGATEPASS = 0x6,
  _Py_ERROR_XMLCHARREFREPLACE = 0x7,
  _Py_ERROR_OTHER = 0x8,
};

/* 222 */
struct __declspec(align(8)) $D047E97CCB2BB87399FC4CB382F586DE
{
  unsigned __int8 *encoding;
  unsigned __int8 *errors;
  _Py_error_handler error_handler;
};

/* 211 */
struct PyWideStringList
{
  __int64 length;
  wchar_t **items;
};

/* 223 */
struct PyConfig
{
  int _config_init;
  int isolated;
  int use_environment;
  int dev_mode;
  int install_signal_handlers;
  int use_hash_seed;
  unsigned int hash_seed;
  int faulthandler;
  int tracemalloc;
  int import_time;
  int show_ref_count;
  int show_alloc_count;
  int dump_refs;
  int malloc_stats;
  wchar_t *filesystem_encoding;
  wchar_t *filesystem_errors;
  wchar_t *pycache_prefix;
  int parse_argv;
  PyWideStringList argv;
  wchar_t *program_name;
  PyWideStringList xoptions;
  PyWideStringList warnoptions;
  int site_import;
  int bytes_warning;
  int inspect;
  int interactive;
  int optimization_level;
  int parser_debug;
  int write_bytecode;
  int verbose;
  int quiet;
  int user_site_directory;
  int configure_c_stdio;
  int buffered_stdio;
  wchar_t *stdio_encoding;
  wchar_t *stdio_errors;
  int legacy_windows_stdio;
  wchar_t *check_hash_pycs_mode;
  int pathconfig_warnings;
  wchar_t *pythonpath_env;
  wchar_t *home;
  int module_search_paths_set;
  PyWideStringList module_search_paths;
  wchar_t *executable;
  wchar_t *base_executable;
  wchar_t *prefix;
  wchar_t *base_prefix;
  wchar_t *exec_prefix;
  wchar_t *base_exec_prefix;
  int skip_source_first_line;
  wchar_t *run_command;
  wchar_t *run_module;
  wchar_t *run_filename;
  int _install_importlib;
  int _init_main;
};

/* 224 */
struct __declspec(align(8)) _warnings_runtime_state
{
  _object *filters;
  _object *once_registry;
  _object *default_action;
  int filters_version;
};

/* 218 */
struct _is
{
  _is *next;
  _ts *tstate_head;
  __int64 id;
  __int64 id_refcount;
  int requires_idref;
  void *id_mutex;
  int finalizing;
  _object *modules;
  _object *modules_by_index;
  _object *sysdict;
  _object *builtins;
  _object *importlib;
  int check_interval;
  int num_threads;
  unsigned __int64 pythread_stacksize;
  _object *codec_search_path;
  _object *codec_search_cache;
  _object *codec_error_registry;
  int codecs_initialized;
  $D047E97CCB2BB87399FC4CB382F586DE fs_codec;
  PyConfig config;
  _object *dict;
  _object *builtins_copy;
  _object *import_func;
  _object *(__fastcall *eval_frame)(_frame *, int);
  __int64 co_extra_user_count;
  void (__fastcall *co_extra_freefuncs[255])(void *);
  void (__fastcall *pyexitfunc)(_object *);
  _object *pyexitmodule;
  unsigned __int64 tstate_next_unique_id;
  _warnings_runtime_state warnings;
  _object *audit_hooks;
};

/* 219 */
struct _ts
{
  _ts *prev;
  _ts *next;
  _is *interp;
  _frame *frame;
  int recursion_depth;
  unsigned __int8 overflowed;
  unsigned __int8 recursion_critical;
  int stackcheck_counter;
  int tracing;
  int use_tracing;
  int (__fastcall *c_profilefunc)(_object *, _frame *, int, _object *);
  int (__fastcall *c_tracefunc)(_object *, _frame *, int, _object *);
  _object *c_profileobj;
  _object *c_traceobj;
  _object *curexc_type;
  _object *curexc_value;
  _object *curexc_traceback;
  _err_stackitem exc_state;
  _err_stackitem *exc_info;
  _object *dict;
  int gilstate_counter;
  _object *async_exc;
  unsigned int thread_id;
  int trash_delete_nesting;
  _object *trash_delete_later;
  void (__fastcall *on_delete)(void *);
  void *on_delete_data;
  int coroutine_origin_tracking_depth;
  _object *async_gen_firstiter;
  _object *async_gen_finalizer;
  _object *context;
  unsigned __int64 context_ver;
  unsigned __int64 id;
};

/* 221 */
struct PyTryBlock
{
  int b_type;
  int b_handler;
  int b_level;
};

/* 220 */
struct _frame
{
  PyVarObject ob_base;
  _frame *f_back;
  PyCodeObject *f_code;
  _object *f_builtins;
  _object *f_globals;
  _object *f_locals;
  _object **f_valuestack;
  _object **f_stacktop;
  _object *f_trace;
  unsigned __int8 f_trace_lines;
  unsigned __int8 f_trace_opcodes;
  _object *f_gen;
  int f_lasti;
  int f_lineno;
  int f_iblock;
  unsigned __int8 f_executing;
  PyTryBlock f_blockstack[20];
  _object *f_localsplus[1];
};

/* 225 */
struct __declspec(align(8)) Nuitka_MetaPathBasedLoaderEntry
{
  const unsigned __int8 *name;
  _object *(__fastcall *python_initfunc)(_ts *, _object *, const Nuitka_MetaPathBasedLoaderEntry *);
  int bytecode_index;
  int bytecode_size;
  int flags;
};

/* 239 */
struct __declspec(align(8)) Nuitka_FrameObject
{
  _frame m_frame;
  const unsigned __int8 *m_type_description;
  unsigned __int8 m_locals_storage[1];
};

/* 240 */
struct Nuitka_CellObject
{
  _object ob_base;
  _object *ob_ref;
};

/* 241 */
struct Nuitka_LoaderObject
{
  _object ob_base;
  const Nuitka_MetaPathBasedLoaderEntry *m_loader_entry;
};

/* 242 */
struct Nuitka_FunctionObject
{
  PyVarObject ob_base;
  _object *m_name;
  _object *m_module;
  _object *m_doc;
  PyCodeObject *m_code_object;
  __int64 m_args_overall_count;
  __int64 m_args_positional_count;
  __int64 m_args_keywords_count;
  bool m_args_simple;
  __int64 m_args_star_list_index;
  __int64 m_args_star_dict_index;
  __int64 m_args_pos_only_count;
  _object **m_varnames;
  _object *(__fastcall *m_c_code)(_ts *, const Nuitka_FunctionObject *, _object **);
  _object *(__fastcall *m_vectorcall)(_object *, _object *const *, unsigned __int64, _object *);
  _object *m_dict;
  _object *m_weakrefs;
  _object *m_defaults;
  __int64 m_defaults_given;
  _object *m_kwdefaults;
  _object *m_annotations;
  _object *m_qualname;
  _object *m_constant_return_value;
  int m_counter;
  __int64 m_closure_given;
  Nuitka_CellObject *m_closure[1];
};

/* 243 */
struct _traceback
{
  _object ob_base;
  _traceback *tb_next;
  _frame *tb_frame;
  int tb_lasti;
  int tb_lineno;
};

/* 244 */
struct Nuitka_MethodObject
{
  _object ob_base;
  Nuitka_FunctionObject *m_function;
  _object *m_weakrefs;
  _object *m_object;
  _object *m_class;
  _object *(__fastcall *m_vectorcall)(_object *, _object *const *, unsigned __int64, _object *);
};

/* 245 */
struct Nuitka_ExceptionStackItem
{
  _object *exception_type;
  _object *exception_value;
  _traceback *exception_tb;
};

/* 246 */
struct Nuitka_GeneratorObject
{
  PyVarObject ob_base;
  _object *m_name;
  _object *m_module;
  _object *m_qualname;
  _object *m_yieldfrom;
  _object *m_weakrefs;
  int m_running;
  void *m_code;
  Nuitka_FrameObject *m_frame;
  PyCodeObject *m_code_object;
  int m_status;
  Nuitka_ExceptionStackItem m_exc_state;
  int m_yield_return_index;
  _object *m_returned;
  int m_counter;
  void *m_heap_storage;
  __int64 m_closure_given;
  Nuitka_CellObject *m_closure[1];
};

/* 247 */
struct Nuitka_CoroutineObject
{
  PyVarObject ob_base;
  _object *m_name;
  _object *m_module;
  _object *m_qualname;
  _object *m_yieldfrom;
  _object *m_weakrefs;
  int m_running;
  int m_awaiting;
  void *m_code;
  Nuitka_FrameObject *m_frame;
  PyCodeObject *m_code_object;
  _frame *m_resume_frame;
  int m_status;
  Nuitka_ExceptionStackItem m_exc_state;
  _object *m_origin;
  int m_yield_return_index;
  _object *m_returned;
  int m_counter;
  void *m_heap_storage;
  __int64 m_closure_given;
  Nuitka_CellObject *m_closure[1];
};

/* 248 */
struct Nuitka_CoroutineWrapperObject
{
  _object ob_base;
  Nuitka_CoroutineObject *m_coroutine;
};

/* 249 */
struct Nuitka_AIterWrapper
{
  _object ob_base;
  _object *aw_aiter;
};

/* 250 */
struct Nuitka_AsyncgenObject
{
  PyVarObject ob_base;
  _object *m_name;
  _object *m_module;
  _object *m_qualname;
  _object *m_yieldfrom;
  _object *m_weakrefs;
  int m_running;
  int m_awaiting;
  int m_running_async;
  void *m_code;
  Nuitka_FrameObject *m_frame;
  PyCodeObject *m_code_object;
  _frame *m_resume_frame;
  int m_status;
  Nuitka_ExceptionStackItem m_exc_state;
  int m_yield_return_index;
  _object *m_finalizer;
  bool m_hooks_init_done;
  bool m_closed;
  int m_counter;
  void *m_heap_storage;
  __int64 m_closure_given;
  Nuitka_CellObject *m_closure[1];
};

/* 251 */
struct Nuitka_AsyncgenWrappedValueObject
{
  _object ob_base;
  _object *m_value;
};

/* 67 */
enum AwaitableState : __int32
{
  AWAITABLE_STATE_INIT = 0x0,
  AWAITABLE_STATE_ITER = 0x1,
  AWAITABLE_STATE_CLOSED = 0x2,
};

/* 252 */
struct __declspec(align(8)) Nuitka_AsyncgenAsendObject
{
  _object ob_base;
  Nuitka_AsyncgenObject *m_gen;
  _object *m_sendval;
  AwaitableState m_state;
};

/* 253 */
struct __declspec(align(8)) Nuitka_AsyncgenAthrowObject
{
  _object ob_base;
  Nuitka_AsyncgenObject *m_gen;
  _object *m_args;
  AwaitableState m_state;
};

/* 254 */
struct _PyDictViewObject
{
  _object ob_base;
  PyDictObject *dv_dict;
};

/* 255 */
struct calliterobject
{
  _object ob_base;
  _object *it_callable;
  _object *it_sentinel;
};

/* 256 */
struct seqiterobject
{
  _object ob_base;
  __int64 it_index;
  _object *it_seq;
};

/* 258 */
struct PyGenObject
{
  _object ob_base;
  _frame *gi_frame;
  unsigned __int8 gi_running;
  _object *gi_code;
  _object *gi_weakreflist;
  _object *gi_name;
  _object *gi_qualname;
  _err_stackitem gi_exc_state;
};

/* 266 */
struct PyFloatObject
{
  _object ob_base;
  long double ob_fval;
};

/* 267 */
struct PyTupleObject
{
  PyVarObject ob_base;
  _object *ob_item[1];
};

/* 268 */
struct PyListObject
{
  PyVarObject ob_base;
  _object **ob_item;
  __int64 allocated;
};

/* 270 */
struct PyDictKeyEntry
{
  __int64 me_hash;
  _object *me_key;
  _object *me_value;
};

/* 271 */
struct dictviewobject
{
  _object ob_base;
  PyDictObject *dv_dict;
};

/* 273 */
struct _rangeobject3
{
  _object ob_base;
  _object *start;
  _object *stop;
  _object *step;
  _object *length;
};

/* 274 */
struct $E9029A8F59CF0E9884279145D2814600
{
  PyTupleObject *tuple;
  __int64 tuple_index;
};

/* 275 */
struct $62B6853B11B4091E1F05E2BCDC45EB1A
{
  PyListObject *list;
  __int64 list_index;
};

/* 276 */
union $456CD0A17A79C0B77F3B8D8C9CD40B2A
{
  _object *iter;
  Nuitka_GeneratorObject *generator;
  $E9029A8F59CF0E9884279145D2814600 tuple_data;
  $62B6853B11B4091E1F05E2BCDC45EB1A list_data;
};

/* 278 */
struct __declspec(align(8)) _longobject
{
  PyVarObject ob_base;
  unsigned int ob_digit[1];
};

/* 280 */
struct PyModuleDef_Base
{
  _object ob_base;
  _object *(__fastcall *m_init)();
  __int64 m_index;
  _object *m_copy;
};

/* 281 */
struct PyModuleDef
{
  PyModuleDef_Base m_base;
  const unsigned __int8 *m_name;
  const unsigned __int8 *m_doc;
  __int64 m_size;
  PyMethodDef *m_methods;
  PyModuleDef_Slot *m_slots;
  int (__fastcall *m_traverse)(_object *, int (__fastcall *)(_object *, void *), void *);
  int (__fastcall *m_clear)(_object *);
  void (__fastcall *m_free)(void *);
};

/* 265 */
struct PyModuleDef_Slot
{
  int slot;
  void *value;
};

/* 282 */
struct Nuitka_ResourceReaderFilesObject
{
  _object ob_base;
  const Nuitka_MetaPathBasedLoaderEntry *m_loader_entry;
  _object *m_path;
};

/* 283 */
struct Nuitka_ResourceReaderObject
{
  _object ob_base;
  const Nuitka_MetaPathBasedLoaderEntry *m_loader_entry;
};

/* 1055 */
typedef _object *(__fastcall *coroutine_code)(_ts *, Nuitka_CoroutineObject *, _object *);

/* 1061 */
typedef _object **Nuitka_DictEntryHandle;

/* 1072 */
typedef __int64 (__fastcall *lenfunc)(_object *);

/* 1073 */
typedef int (__fastcall *objobjproc)(_object *, _object *);

/* 1078 */
typedef int (__fastcall *Py_tracefunc)(_object *, _frame *, int, _object *);

/* 1098 */
typedef _object *(__fastcall *binaryfunc)(_object *, _object *);

/* 1100 */
typedef _object *(__fastcall *richcmpfunc)(_object *, _object *, int);

/* 1106 */
typedef _object *(__fastcall *unaryfunc)(_object *);

/* 1125 */
typedef _object *(__fastcall *newfunc)(_typeobject *, _object *, _object *);

/* 1127 */
typedef int (__fastcall *setattrofunc)(_object *, _object *, _object *);

/* 1129 */
typedef _object *(__fastcall *getattrofunc)(_object *, _object *);

/* 1130 */
typedef void (__fastcall *destructor)(_object *);

/* 1131 */
typedef __int64 (__fastcall *dict_lookup_func)(PyDictObject *, _object *, __int64, _object **);

/* 1135 */
typedef _object *(__fastcall *ternaryfunc)(_object *, _object *, _object *);

/* 1137 */
typedef _object *(__fastcall *generator_code)(_ts *, Nuitka_GeneratorObject *, _object *);

/* 1141 */
typedef _object *(__fastcall *vectorcallfunc)(_object *, _object *const *, unsigned __int64, _object *);

/* 1153 */
typedef int (__fastcall *objobjargproc)(_object *, _object *, _object *);

/* 1167 */
typedef _object *(__fastcall *getiterfunc)(_object *);

/* 1180 */
typedef _object *(__fastcall *reprfunc)(_object *);

/* 1191 */
typedef int (__fastcall *inquiry)(_object *);

/* 1193 */
typedef int (__fastcall *getbufferproc)(_object *, bufferinfo *, int);

/* 1195 */
typedef _object *__fastcall unary_api(_object *);

/* 1201 */
typedef _object *(__fastcall *_PyFrameEvalFunction)(_frame *, int);

/* 1202 */
typedef _object *(__fastcall *ssizeargfunc)(_object *, __int64);

/* 1210 */
typedef void (__fastcall *PyCapsule_Destructor)(_object *);

/* 1213 */
typedef int (__fastcall *descrsetfunc)(_object *, _object *, _object *);

/* 1221 */
typedef _object *(__fastcall *function_impl_code)(_ts *, const Nuitka_FunctionObject *, _object **);

/* 1224 */
typedef __int64 (__fastcall *hashfunc)(_object *);

/* 1236 */
typedef _object *(__fastcall *entrypoint_t)();

/* 1267 */
typedef void (__fastcall *releasebufferproc)(_object *, bufferinfo *);

/* 1270 */
typedef _object *(__fastcall *copy_func)(_ts *, _object *);

/* 1271 */
typedef _object *(__fastcall *module_initfunc)(_ts *, _object *, const Nuitka_MetaPathBasedLoaderEntry *);

/* 1283 */
typedef int (__fastcall *visitproc)(_object *, void *);

/* 1296 */
typedef _object *(__fastcall *descrgetfunc)(_object *, _object *, _object *);

/* 1305 */
typedef _object *(__fastcall *allocfunc)(_typeobject *, __int64);

/* 1306 */
typedef int (__fastcall *ssizeobjargproc)(_object *, __int64, _object *);

/* 1316 */
typedef _object *(__fastcall *getattrfunc)(_object *, unsigned __int8 *);

/* 1320 */
typedef int (__fastcall *setattrfunc)(_object *, unsigned __int8 *, _object *);

/* 1325 */
typedef _object *(__fastcall *asyncgen_code)(_ts *, Nuitka_AsyncgenObject *, _object *);

/* 1331 */
typedef int (__fastcall *GetUserObjectInformationW_pft)(void *, int, void *, unsigned int, unsigned int *);

/* 1340 */
typedef int (__fastcall *traverseproc)(_object *, int (__fastcall *)(_object *, void *), void *);

/* 1341 */
typedef int (__fastcall *setter)(_object *, _object *, void *);

/* 1342 */
typedef _object *(__fastcall *getter)(_object *, void *);

/* 1344 */
typedef _object *PyDictValues;

/* 1347 */
typedef _object *(__fastcall *PyCFunction)(_object *, _object *);

/* 1373 */
typedef _object *(__fastcall *iternextfunc)(_object *);

/* 1376 */
typedef _object *(__fastcall *Py_OpenCodeHookFunction)(_object *, void *);

/* 1388 */
typedef int (__fastcall *initproc)(_object *, _object *, _object *);

/* 1392 */
typedef int (__fastcall *python_initproc)(_object *, _object *, _object *);


// MANUALLY ADDED
#define PyObject_HEAD          PyObject ob_base;
#define PyObject_VAR_HEAD      PyVarObject ob_base;

typedef struct _object PyObject;
typedef struct _longobject PyLongObject;
typedef struct _typeobject PyTypeObject;
typedef struct _frame PyFrameObject;

typedef struct _ts PyThreadState;
typedef struct _is PyInterpreterState;

typedef struct _dictkeysobject PyDictKeysObject;
typedef struct _dictvalues PyDictValues;

struct PyBytesObject {
  PyObject_VAR_HEAD
  __int64 ob_shash;
  char ob_sval[1];
};


// https://github.com/python/cpython/issues/87090
struct PyByteArrayObject {
  PyObject_VAR_HEAD
  __int64 ob_alloc; // number of bytes in ob_bytes
  char *ob_bytes; // physical backing buffer (i.e. original buffer)
  char *ob_start; // logical start inside ob_bytes (i.e. current buffer)
  __int64 ob_exports;
};


struct PyFloatObject {
  PyObject_HEAD
  double ob_fval;
};


struct PySliceObject {
  PyObject_HEAD
  PyObject *start, *stop, *step;
};


struct setentry {
  _object *key;
  __int64 hash;
};

struct PySetObject
{
  PyObject_HEAD
  __int64 fill;
  __int64 used;
  __int64 mask;
  setentry *table;
  __int64 hash;
  __int64 finger;
  setentry smalltable[8];
  _object *weakreflist;
};


struct PyModuleObject {
  PyObject_HEAD
  _object *md_dict; // module dict
  PyModuleDef *md_def;
  void *md_state;
  _object *md_weaklist;
  _object *md_name; // module name
};
